# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  browser:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: nuget install Selenium.WebDriver.IEDriver -Version 3.150.0
      - run: npm run test:browser
        env:
          BROWSER: ie

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        ts-project: [src/tsconfig.json, src/tsconfig-es6.json]

    env:
      TS_NODE_PROJECT: ${{ matrix.ts-project }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm cache clean --force
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
